#Created on Thu Nov 14 06:35:10 2019
#author: Shaqlin Mustak(9codes)
print("***Wellcome***")
print("***You are going to add first integer to second integer!!!***")
print("***And you must type an integer in the input box to get valid result.***")
number1 = input("Please type first integer:")
number2 = input("Please type second integer:")
number1 = int(number1)
number2 = int(number2)
print(number1,"+",number2,"=",number1+number2)
